import type { ExtractedColors } from "../src/dominantColor";

/**
 * Renders the precomputed cover colors as the full source of `src/albumColors.ts`
 * -- a generated map keyed by `coverArtUrl`. Kept separate from the `Album` shape
 * and `serializeAlbums` so precompute is purely additive and never touches the
 * curation pipeline. Entry order is preserved for stable diffs.
 */
export function serializeAlbumColors(
  entries: Array<[string, ExtractedColors]>,
): string {
  const body = entries
    .map(
      ([url, c]) =>
        `  ${JSON.stringify(url)}: { primary: ${JSON.stringify(c.primary)}, secondary: ${JSON.stringify(c.secondary)} },`,
    )
    .join("\n");

  return [
    "// GENERATED by scripts/precomputeColorsCli.ts -- do not edit by hand.",
    "// Run `npm run curate:colors` to regenerate after the album list changes.",
    'import type { ExtractedColors } from "./dominantColor";',
    "",
    "export const albumColors: Record<string, ExtractedColors> = {",
    body,
    "};",
    "",
  ].join("\n");
}
