import { describe, expect, it } from "vitest";
import { serializeAlbumColors } from "./serializeAlbumColors";
import type { ExtractedColors } from "../src/dominantColor";

describe("serializeAlbumColors", () => {
  it("renders a valid generated module keyed by cover url", () => {
    const entries: Array<[string, ExtractedColors]> = [
      ["https://example.com/art.jpg", { primary: "#ff5a36", secondary: "#1a1a1a" }],
    ];

    expect(serializeAlbumColors(entries)).toBe(
      `// GENERATED by scripts/precomputeColorsCli.ts -- do not edit by hand.
// Run \`npm run curate:colors\` to regenerate after the album list changes.
import type { ExtractedColors } from "./dominantColor";

export const albumColors: Record<string, ExtractedColors> = {
  "https://example.com/art.jpg": { primary: "#ff5a36", secondary: "#1a1a1a" },
};
`,
    );
  });

  it("renders multiple entries in order", () => {
    const entries: Array<[string, ExtractedColors]> = [
      ["a", { primary: "#111111", secondary: "#222222" }],
      ["b", { primary: "#333333", secondary: "#444444" }],
    ];

    const out = serializeAlbumColors(entries);
    const aIndex = out.indexOf('"a":');
    const bIndex = out.indexOf('"b":');

    expect(aIndex).toBeGreaterThan(-1);
    expect(bIndex).toBeGreaterThan(aIndex);
  });
});
